apiVersion: v1
kind: Service
metadata:
  name: kube-test-service
spec:
  type: NodePort
  selector:
    app: kube-test
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
  
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-test-deploy
spec:
  selector:
    matchLabels:
      app: kube-test
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-test
    spec:
      containers:
      - image: krstphr/kube-test
        imagePullPolicy: Always
        name: kube-test
        ports:
        - containerPort: 3000

